//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fatura()
        {
            this.FaturaDetay = new HashSet<FaturaDetay>();
            this.Siparis_Fatura = new HashSet<Siparis_Fatura>();
            this.Fatura_Odeme = new HashSet<Fatura_Odeme>();
        }
    
        public long No { get; set; }
        public string FisNumarasi { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public Nullable<int> CariNo { get; set; }
        public Nullable<decimal> NetTutar { get; set; }
        public Nullable<decimal> ToplamKdvTutari { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<int> KullaniciNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Cari Cari { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaDetay> FaturaDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis_Fatura> Siparis_Fatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura_Odeme> Fatura_Odeme { get; set; }
    }
}
