//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
            this.Siparis_Fatura = new HashSet<Siparis_Fatura>();
        }
    
        public long No { get; set; }
        public string Kod { get; set; }
        public Nullable<int> CariNo { get; set; }
        public Nullable<int> KullaniciNo { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Cari Cari { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis_Fatura> Siparis_Fatura { get; set; }
    }
}
